spring:
  datasource:
    url: jdbc:postgresql://ep-cool-base-adv91zvu-pooler.c-2.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_cCiaPJu3oE5F
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
